apiVersion: v1
kind: ConfigMap
metadata:
  name: sub-indexer-gw-env
  namespace: sub-back
data:

  server_port: "8080"

  SERVER_PORT: "8080"

  
  SERVER: "8080"
  


  PROJECT_NAME: "subsocial-hydra"

  TYPEORM_LOGGING: "error"

  CHAIN_NODE: "wss://arch.subsocial.network"


  INDEXER_ENDPOINT_URL: "http://sub-indexer-gw:4000/v1/graphql"

  BATCH_SIZE: "500"
  BLOCK_WINDOW: "100000"

  GRAPHQL_SERVER_PORT: "8080"


  WARTHOG_STARTER_DB_DATABASE: "subsocial_indexer_usr"
  WARTHOG_STARTER_DB_HOST: "10.110.0.2"
  WARTHOG_STARTER_DB_PORT: "5432"
  WARTHOG_STARTER_DB_USERNAME: "subsocial_indexer_usr"
  WARTHOG_STARTER_DB_PASSWORD: "190dsfg7rhPOi"
  WARTHOG_STARTER_REDIS_URI: "redis://redis:6379/0"
  PORT: "8080"


  DB_HOST: "10.110.0.2"
  DB_NAME: "subsocial_indexer_usr"
  DB_USER: "subsocial_indexer_usr"
  DB_PASS: "190dsfg7rhPOi"
  DB_PORT: "5432"
  DEV_MODE: "true"
  HYDRA_INDEXER_STATUS_SERVICE: "http://indexer-status-service:8081/status"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sub-indexer-status-env
  namespace: sub-back
data:

 REDIS_URI: "redis://redis:6379/0"
 PORT: "8081"


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-indexer-status
  namespace: sub-back
  labels:
    app: sub-indexer-status
spec:
  replicas: 1
  template:
    metadata:
      name: sub-indexer-status
      labels:
        app: sub-indexer-status
    spec:
      containers:
        - name: sub-indexer-status
          image: subsquid/hydra-indexer-status-service:4 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: sub-indexer-status-env


      restartPolicy: Always
  selector:
    matchLabels:
      app: sub-indexer-status


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-indexer-gw
  namespace: sub-back
  labels:
    app: sub-indexer-gw
spec:
  replicas: 1
  template:
    metadata:
      name: sub-indexer-gw
      labels:
        app: sub-indexer-gw
    spec:
      containers:
        - name: sub-indexer-gw
          image: subsquid/hydra-indexer-gateway:4 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sub-indexer-gw-env


      restartPolicy: Always
  selector:
    matchLabels:
      app: sub-indexer-gw


      
