apiVersion: v1
kind: ConfigMap
metadata:
  name: sub-indexer-env
  namespace: sub-back
data:

  INDEXER_WORKERS: "5"

# PostgreSQL config
  DB_HOST: "10.110.0.2"
  DB_NAME: "subsocial_indexer_usr"
  DB_USER: "subsocial_indexer_usr"
  DB_PASS: "190dsfg7rhPOi"
  DB_PORT: "5432"


  REDIS_URI: "redis://redis:6379/0"


  DEBUG: "index*"
  BLOCK_HEIGHT: "658170"
  BUNDLE_TYPES: "typesBundle.json"
  WS_PROVIDER_ENDPOINT_URI: "wss://arch.subsocial.network"

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-indexer
  namespace: sub-back
  labels:
    app: sub-indexer
spec:
  replicas: 1
  template:
    metadata:
      name: sub-indexer
      labels:
        app: sub-indexer
    spec:
      volumes:
      - name: node
        persistentVolumeClaim:
          claimName: stage-indexer-pvc
      containers:
        - name: sub-indexer
          image: subsquid/hydra-indexer:4
          imagePullPolicy: IfNotPresent
          command:
            ['sh', '-c', 'yarn db:bootstrap && yarn start:prod']
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sub-indexer-env
          volumeMounts:
           - name: node
             mountPath: /hydra/packages/hydra-indexer/typesBundle.json
             subPath: ./typesBundle.json


      restartPolicy: Always
  selector:
    matchLabels:
      app: sub-indexer

